version: '3.7'

services:
  mofupifm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mofupifm
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: tail -f /dev/null
    networks:
      - default

